spring:
  application:
    name: project
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
      include:
        mapper: cn/edu/nju/software/**/mapper-[\\w-\\.]+jar
  # the max size of upload file
  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 500MB
  mail:
    host: smtp.163.com
    username: iammengfengfei@163.com
    password: WangDong0719
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# common config
# datasource with druid through mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.89.98:3306/ai_platform?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: aiuser
    password: aiuser
    sql-script-encoding: UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 6000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    #druid StatViewServlet监控配置
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow:
        deny:
        aop-patterns:
        # aop-patterns: cn.edu.nju.software.**.service

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,*.html'
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name:
        principal-cookie-name:
        profile-enable:
  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    mode: HTML5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


# mybatis_config
mybatis:
    # entity_package
    type-aliases-package: cn.edu.nju.software
    # Mapper.xml
    mapper-locations: classpath:mybatis/mapper/*Mapper.xml
    #    configuration:
    #        map-underscore-to-camel-case: true
    #        default-fetch-size: 100
    #        default-statement-timeout: 30
    # mybatis-enhance-actable config
    configuration:
      map-underscore-to-camel-case: true
    table:
      auto: update
    model:
      pack: cn.edu.nju.software.entity
    database:
      type: mysql
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  not-empty: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
# logging config
logging:
  config: classpath:logback.xml

# session默认30min 设置为60min
server:
  session:
    timeout: 60
#  redis:
#    database: 6
#    host: 192.168.103.202
#    password:
#    port: 6379
#    pool:
#      max-idle: 8
#      min-idle: 0
#      max-active: 8
#      max-wait: -1


# 根据部署的系统选择所要上传的目录在哪
upload:
  folder: home/upload/

python:
  img:
    path: /home/dl/Documents/FastPhotoStyle

video-stream:
  ip: localhost
  port: 5080
